// default package
// Generated Jul 10, 2016 7:22:32 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupAuthorities generated by hbm2java
 */
@Entity
@Table(name = "group_authorities", catalog = "OAuth")
public class GroupAuthorities implements java.io.Serializable {

	private GroupAuthoritiesId id;

	public GroupAuthorities() {
	}

	public GroupAuthorities(GroupAuthoritiesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)),
			@AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 50)) })
	public GroupAuthoritiesId getId() {
		return this.id;
	}

	public void setId(GroupAuthoritiesId id) {
		this.id = id;
	}

}
