// default package
// Generated Jul 10, 2016 7:22:32 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupAuthoritiesId generated by hbm2java
 */
@Embeddable
public class GroupAuthoritiesId implements java.io.Serializable {

	private long groupId;
	private String authority;

	public GroupAuthoritiesId() {
	}

	public GroupAuthoritiesId(long groupId, String authority) {
		this.groupId = groupId;
		this.authority = authority;
	}

	@Column(name = "group_id", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Column(name = "authority", nullable = false, length = 50)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupAuthoritiesId))
			return false;
		GroupAuthoritiesId castOther = (GroupAuthoritiesId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& ((this.getAuthority() == castOther.getAuthority()) || (this.getAuthority() != null
						&& castOther.getAuthority() != null && this.getAuthority().equals(castOther.getAuthority())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGroupId();
		result = 37 * result + (getAuthority() == null ? 0 : this.getAuthority().hashCode());
		return result;
	}

}
