// default package
// Generated Jul 10, 2016 7:22:32 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OauthCode generated by hbm2java
 */
@Entity
@Table(name = "oauth_code", catalog = "OAuth")
public class OauthCode implements java.io.Serializable {

	private OauthCodeId id;

	public OauthCode() {
	}

	public OauthCode(OauthCodeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "code", column = @Column(name = "code", length = 256)),
			@AttributeOverride(name = "authentication", column = @Column(name = "authentication")) })
	public OauthCodeId getId() {
		return this.id;
	}

	public void setId(OauthCodeId id) {
		this.id = id;
	}

}
