// default package
// Generated Jul 10, 2016 7:22:32 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OauthApprovals generated by hbm2java
 */
@Entity
@Table(name = "oauth_approvals", catalog = "OAuth")
public class OauthApprovals implements java.io.Serializable {

	private OauthApprovalsId id;

	public OauthApprovals() {
	}

	public OauthApprovals(OauthApprovalsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userId", length = 256)),
			@AttributeOverride(name = "clientId", column = @Column(name = "clientId", length = 256)),
			@AttributeOverride(name = "scope", column = @Column(name = "scope", length = 256)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 10)),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expiresAt", nullable = false, length = 19)) })
	public OauthApprovalsId getId() {
		return this.id;
	}

	public void setId(OauthApprovalsId id) {
		this.id = id;
	}

}
