// default package
// Generated Jul 10, 2016 7:22:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OauthApprovalsId generated by hbm2java
 */
@Embeddable
public class OauthApprovalsId implements java.io.Serializable {

	private String userId;
	private String clientId;
	private String scope;
	private String status;
	private Date expiresAt;

	public OauthApprovalsId() {
	}

	public OauthApprovalsId(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public OauthApprovalsId(String userId, String clientId, String scope, String status, Date expiresAt) {
		this.userId = userId;
		this.clientId = clientId;
		this.scope = scope;
		this.status = status;
		this.expiresAt = expiresAt;
	}

	@Column(name = "userId", length = 256)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "clientId", length = 256)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "scope", length = 256)
	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "expiresAt", nullable = false, length = 19)
	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OauthApprovalsId))
			return false;
		OauthApprovalsId castOther = (OauthApprovalsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getClientId() == castOther.getClientId()) || (this.getClientId() != null
						&& castOther.getClientId() != null && this.getClientId().equals(castOther.getClientId())))
				&& ((this.getScope() == castOther.getScope()) || (this.getScope() != null
						&& castOther.getScope() != null && this.getScope().equals(castOther.getScope())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getExpiresAt() == castOther.getExpiresAt()) || (this.getExpiresAt() != null
						&& castOther.getExpiresAt() != null && this.getExpiresAt().equals(castOther.getExpiresAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result + (getScope() == null ? 0 : this.getScope().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getExpiresAt() == null ? 0 : this.getExpiresAt().hashCode());
		return result;
	}

}
